variables:
  FACTORY_PRODUCT_NAME: pgrouting
  FACTORY_PACKAGE_TYPE: module
  POSTGRES_DB: "lizmap"
  POSTGRES_USER: "lizmap"
  POSTGRES_PASSWORD: "lizmap1234!"
  POSTGRES_HOST: "db"

stages:
- Tests 🎳
- Release 🚀

sql:
  stage: Tests 🎳
  parallel:
    matrix:
      - PG_VERSION: [11-2.5, 13-3]
  services:
    - name: $REGISTRY_URI/postgis:${PG_VERSION}
      alias: db
  image:
    name: $REGISTRY_URI/factory-ci-base:python-3.9
  before_script:
    - export PATH=/root/.local/bin:$PATH
    - pip3 install --user -r requirements/tests.txt
    - cd tests/sql
  script:
    - pytest -v
  tags:
    - factory-dind

tickets:
  stage: Release 🚀
  only:
    - tags
  image:
    name: $REGISTRY_URI/infra/ci-tools:latest
  script:
    - create_ticket.py
  tags:
    - factory-plain

gitlab_release:
  stage: Release 🚀
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
      # Running only when the tag is like X.Y.Z
      when: always
    - when: never
  image:
    name: $REGISTRY_URI/infra/ci-tools:latest
  script:
    - gitlab_release
  tags:
    - factory-plain
