variables:
  FACTORY_PRODUCT_NAME: pgrouting
  FACTORY_PACKAGE_TYPE: module
  POSTGRES_DB: "lizmap"
  POSTGRES_USER: "lizmap"
  POSTGRES_PASSWORD: "lizmap1234!"
  POSTGRES_HOST: "db"

stages:
- Tests 🎳
- Release 🚀

sql:
  stage: Tests 🎳
  parallel:
    matrix:
      - PG_VERSION: [11-2.5, 13-3]
  services:
    - name: registry.snap.lizlan:5000/postgis:${PG_VERSION}
      alias: db
  image:
    name: registry.snap.lizlan:5000/python:3.9
  before_script:
    - pip3 install --user -r requirements/tests.txt
    - cd tests/sql
  script:
    - pytest -v
  tags:
    - factory-dnd

tickets:
  stage: Release 🚀
  only:
    - tags
  image:
    name: registry.snap.lizlan:5000/infra/ci-tools:latest
  script:
    - create_ticket.py
  tags:
    - factory-plain
