name: Tests 🎳

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:

jobs:
  sql:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg_version: [
            "11-2.5",
            "13-3",
        ]
    env:
      POSTGRES_DB: "lizmap"
      POSTGRES_USER: "lizmap"
      POSTGRES_PASSWORD: "lizmap1234!"
      POSTGRES_HOST: "localhost"

    services:
      postgres:
        image: 3liz/postgis:${{ matrix.pg_version }}
        env:
          POSTGRES_USER: "lizmap"
          POSTGRES_PASSWORD: "lizmap1234!"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/tests.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: pip install -r requirements/tests.txt

      - name: Run tests
        working-directory: tests/sql
        run: |
          pytest -v

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ sql ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/packaging.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: pip install -r requirements/packaging.txt

      - name : Get current changelog
        run: qgis-plugin-ci changelog ${{ env.RELEASE_VERSION }} >> release.md

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.8.9
        with:
          bodyFile: release.md
          token: ${{ secrets.BOT_HUB_TOKEN }}

      - name: Tweet
        uses: mugi111/tweet-trigger-release@v1.2
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: "New version of the #PgRouting 🐘 module ${{ env.RELEASE_VERSION }} for @LizmapForQgis 🦎 https://github.com/3liz/lizmap-pgrouting-module/releases"
