name: Tests 🎳

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:

jobs:
  sql:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg_version: [
            "13-3",
            "15-3"
        ]
    env:
      POSTGRES_DB: "lizmap"
      POSTGRES_USER: "lizmap"
      POSTGRES_PASSWORD: "lizmap1234!"
      POSTGRES_HOST: "localhost"

    services:
      postgres:
        image: 3liz/postgis:${{ matrix.pg_version }}
        env:
          POSTGRES_USER: "lizmap"
          POSTGRES_PASSWORD: "lizmap1234!"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install Python requirements
        run: pip install -r requirements/tests.txt

      - name: Run tests
        working-directory: tests/sql
        run: |
          pytest -v

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ sql ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Read the changelog
        id: changelog
        uses: Gustry/changelog-release@0.1.0
        with:
          tag_name: ${{ env.RELEASE_VERSION }}

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.11.1
        with:
          body: ${{ steps.changelog.outputs.markdown }}
          token: ${{ secrets.BOT_HUB_TOKEN }}

      - name: Tweet
        uses: mugi111/tweet-trigger-release@v1.2
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: "New version of the #PgRouting 🐘 module ${{ env.RELEASE_VERSION }} for @LizmapForQgis 🦎 https://github.com/3liz/lizmap-pgrouting-module/releases"
